CREATE TABLE vs_user_role (
    user_role_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code         VARCHAR2(55) NOT NULL,
    description  VARCHAR2(55) NOT NULL,
    CONSTRAINT uq_user_role_code UNIQUE ( code ),
    CONSTRAINT uq_user_role_description UNIQUE ( description )
);

CREATE TABLE vs_user_account (
    user_account_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email           VARCHAR2(255) NOT NULL,
    hashed_password VARCHAR2(255) NOT NULL,
    phone           VARCHAR2(15),
    user_role_id    NUMBER NOT NULL,
    CONSTRAINT uq_user_account_email UNIQUE ( email ),
    CONSTRAINT fk_user_account_user_role FOREIGN KEY ( user_role_id )
        REFERENCES vs_user_role ( user_role_id )
);

CREATE TABLE vs_shipper (
    shipper_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type             VARCHAR2(2) CHECK ( type IN ( 'PF',
                                       'PJ' ) ) NOT NULL,
    shipper_document VARCHAR(14) NOT NULL,
    name             VARCHAR2(255) NOT NULL,
    user_account_id  NUMBER NOT NULL,
    CONSTRAINT uq_shipper_document UNIQUE ( shipper_document ),
    CONSTRAINT fk_shipper_user_account FOREIGN KEY ( user_account_id )
        REFERENCES vs_user_account ( user_account_id )
);

CREATE TABLE vs_launch_provider (
    launch_provider_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cnpj               VARCHAR2(14) NOT NULL,
    corporate_name     VARCHAR2(255) NOT NULL,
    user_account_id    NUMBER NOT NULL,
    CONSTRAINT uq_launch_provider_cnpj UNIQUE ( cnpj ),
    CONSTRAINT fk_launch_provider_user_account FOREIGN KEY ( user_account_id )
        REFERENCES vs_user_account ( user_account_id )
);

CREATE TABLE vs_operator_status (
    operator_status_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code               VARCHAR2(55) NOT NULL,
    description        VARCHAR2(55) NOT NULL,
    CONSTRAINT uq_operator_status_code UNIQUE ( code ),
    CONSTRAINT uq_operator_status_description UNIQUE ( description )
);

CREATE TABLE vs_operator (
    operator_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    launch_provider_id NUMBER NOT NULL,
    cpf                VARCHAR2(11) NOT NULL,
    name               VARCHAR2(255) NOT NULL,
    user_account_id    NUMBER NOT NULL,
    operator_status_id NUMBER NOT NULL,
    CONSTRAINT uq_operator_cpf UNIQUE ( cpf ),
    CONSTRAINT fk_operator_launch_provider FOREIGN KEY ( launch_provider_id )
        REFERENCES vs_launch_provider ( launch_provider_id ),
    CONSTRAINT fk_operator_user_account FOREIGN KEY ( user_account_id )
        REFERENCES vs_user_account ( user_account_id ),
    CONSTRAINT fk_operator_status FOREIGN KEY ( operator_status_id )
        REFERENCES vs_operator_status ( operator_status_id )
);

CREATE TABLE vs_satellite_status (
    satellite_status_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code                VARCHAR2(55) NOT NULL,
    description         VARCHAR2(55) NOT NULL,
    CONSTRAINT uq_satellite_status_code UNIQUE ( code ),
    CONSTRAINT uq_satellite_status_description UNIQUE ( description )
);

CREATE TABLE vs_satellite_priority (
    satellite_priority_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    priority_level        NUMBER NOT NULL,
    description           VARCHAR2(55) NOT NULL,
    CONSTRAINT uq_satellite_priority_description UNIQUE ( description ),
    CONSTRAINT uq_satellite_priority_level UNIQUE ( priority_level )
);

CREATE TABLE vs_rocket_status (
    rocket_status_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code             VARCHAR2(55) NOT NULL,
    description      VARCHAR2(55) NOT NULL,
    CONSTRAINT uq_rocket_status_code UNIQUE ( code ),
    CONSTRAINT uq_rocket_status_description UNIQUE ( description )
);

CREATE TABLE vs_rocket (
    rocket_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name             VARCHAR2(55) NOT NULL,
    capacity_height  NUMBER NOT NULL,
    capacity_width   NUMBER NOT NULL,
    capacity_length  NUMBER NOT NULL,
    capacity_weight  NUMBER NOT NULL,
    launch_date      TIMESTAMP,
    rocket_status_id NUMBER NOT NULL,
    CONSTRAINT uq_rocket_name UNIQUE ( name ),
    CONSTRAINT fk_rocket_status FOREIGN KEY ( rocket_status_id )
        REFERENCES vs_rocket_status ( rocket_status_id )
);

CREATE TABLE vs_satellite (
    satellite_id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shipper_id            NUMBER NOT NULL,
    launch_provider_id    NUMBER NOT NULL,
    name                  VARCHAR2(55) NOT NULL,
    height                NUMBER NOT NULL,
    width                 NUMBER NOT NULL,
    length                NUMBER NOT NULL,
    weight                NUMBER NOT NULL,
    launch_justification  VARCHAR2(500) NOT NULL,
    satellite_status_id   NUMBER NOT NULL,
    satellite_priority_id NUMBER,
    tracking_code         VARCHAR2(55),
    rocket_id             NUMBER,
    CONSTRAINT fk_satellite_shipper FOREIGN KEY ( shipper_id )
        REFERENCES vs_shipper ( shipper_id ),
    CONSTRAINT fk_satellite_launch_provider FOREIGN KEY ( launch_provider_id )
        REFERENCES vs_launch_provider ( launch_provider_id ),
    CONSTRAINT fk_satellite_satellite_status FOREIGN KEY ( satellite_status_id )
        REFERENCES vs_satellite_status ( satellite_status_id ),
    CONSTRAINT fk_satellite_priority FOREIGN KEY ( satellite_priority_id )
        REFERENCES vs_satellite_priority ( satellite_priority_id ),
    CONSTRAINT fk_satellite_rocket FOREIGN KEY ( rocket_id )
        REFERENCES vs_rocket ( rocket_id )
);

CREATE TABLE vs_inspection (
    inspection_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    satellite_id    NUMBER NOT NULL,
    operator_id     NUMBER NOT NULL,
    measured_height NUMBER NOT NULL,
    measured_width  NUMBER NOT NULL,
    measured_length NUMBER NOT NULL,
    measured_weight NUMBER NOT NULL,
    result          VARCHAR2(1) CHECK ( result IN ( 'A',
                                           'R' ) ) NOT NULL,
    inspection_date TIMESTAMP DEFAULT systimestamp NOT NULL,
    CONSTRAINT fk_inspection_satellite FOREIGN KEY ( satellite_id )
        REFERENCES vs_satellite ( satellite_id ),
    CONSTRAINT fk_inspection_operator FOREIGN KEY ( operator_id )
        REFERENCES vs_operator ( operator_id )
);